// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recetas.Infraestructura.Persistencia;

#nullable disable

namespace Recetas.Infraestructura.Migrations
{
    [DbContext(typeof(RecetasDbContext))]
    [Migration("20260802175045_CuentasDeUsuario")]
    partial class CuentasDeUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recetas.Dominio.Registro.SolicitudDeRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeCaducidad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_caducidad");

                    b.Property<DateTimeOffset?>("FechaDeConsumo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_consumo");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_del_token");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .HasDatabaseName("ix_solicitudes_correo");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitudes_hash_del_token");

                    b.ToTable("solicitudes_de_registro", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_alta");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash_de_contrasena");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
