// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recetas.Infraestructura.Persistencia;

#nullable disable

namespace Recetas.Infraestructura.Migrations
{
    [DbContext(typeof(RecetasDbContext))]
    [Migration("20260802205215_Recetas")]
    partial class Recetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recetas.Dominio.Recetas.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredientes_nombre");

                    b.ToTable("ingredientes", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.IngredienteDeReceta", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad");

                    b.HasKey("RecetaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ingredientes_de_receta", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Elaboracion")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("elaboracion");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<DateTimeOffset>("FechaDeModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDePlato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_de_plato");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibilidad");

                    b.HasKey("Id");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_recetas_autor");

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Registro.SolicitudDeRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeCaducidad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_caducidad");

                    b.Property<DateTimeOffset?>("FechaDeConsumo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_consumo");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_del_token");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .HasDatabaseName("ix_solicitudes_correo");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitudes_hash_del_token");

                    b.ToTable("solicitudes_de_registro", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_alta");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash_de_contrasena");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.IngredienteDeReceta", b =>
                {
                    b.HasOne("Recetas.Dominio.Recetas.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Receta", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
