// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recetas.Infraestructura.Persistencia;

#nullable disable

namespace Recetas.Infraestructura.Migrations
{
    [DbContext(typeof(RecetasDbContext))]
    [Migration("20260809135101_Etiquetas")]
    partial class Etiquetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recetas.Dominio.Favoritos.Favorito", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<DateTimeOffset>("FechaDeMarca")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_marca");

                    b.HasKey("UsuarioId", "RecetaId");

                    b.HasIndex("RecetaId")
                        .HasDatabaseName("ix_favoritos_receta");

                    b.ToTable("favoritos", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Moderacion.Denuncia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comentario");

                    b.Property<Guid>("DenuncianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("denunciante_id");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.HasIndex("DenuncianteId", "RecetaId")
                        .IsUnique()
                        .HasDatabaseName("ix_denuncias_denunciante_receta");

                    b.ToTable("denuncias", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreParaBusqueda")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombre_para_busqueda");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_etiquetas_nombre");

                    b.HasIndex("NombreParaBusqueda")
                        .HasDatabaseName("ix_etiquetas_nombre_para_busqueda");

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.EtiquetaDeReceta", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etiqueta_id");

                    b.HasKey("RecetaId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("etiquetas_de_receta", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaDeSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_subida");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<long>("TamanoEnBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_en_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId")
                        .HasDatabaseName("ix_fotos_receta");

                    b.ToTable("fotos", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreParaBusqueda")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre_para_busqueda");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredientes_nombre");

                    b.HasIndex("NombreParaBusqueda")
                        .HasDatabaseName("ix_ingredientes_nombre_para_busqueda");

                    b.ToTable("ingredientes", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.IngredienteDeReceta", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("receta_id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad");

                    b.HasKey("RecetaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ingredientes_de_receta", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Elaboracion")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("elaboracion");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<DateTimeOffset>("FechaDeModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreParaBusqueda")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_para_busqueda");

                    b.Property<int?>("Raciones")
                        .HasColumnType("integer")
                        .HasColumnName("raciones");

                    b.Property<string>("TipoDePlato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_de_plato");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibilidad");

                    b.HasKey("Id");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_recetas_autor");

                    b.HasIndex("NombreParaBusqueda")
                        .HasDatabaseName("ix_recetas_nombre_para_busqueda");

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Registro.SolicitudDeRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeCaducidad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_caducidad");

                    b.Property<DateTimeOffset?>("FechaDeConsumo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_consumo");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_del_token");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .HasDatabaseName("ix_solicitudes_correo");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitudes_hash_del_token");

                    b.ToTable("solicitudes_de_registro", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Usuarios.SolicitudDeContrasena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaDeCaducidad")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_caducidad");

                    b.Property<DateTimeOffset?>("FechaDeConsumo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_consumo");

                    b.Property<DateTimeOffset>("FechaDeCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_creacion");

                    b.Property<string>("HashDelToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_del_token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("HashDelToken")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitudes_contrasena_hash_del_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_solicitudes_contrasena_usuario");

                    b.ToTable("solicitudes_de_contrasena", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaDeAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_alta");

                    b.Property<DateTimeOffset?>("FechaDeCambioDeContrasena")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_cambio_de_contrasena");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash_de_contrasena");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Recetas.Dominio.Favoritos.Favorito", b =>
                {
                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetas.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetas.Dominio.Moderacion.Denuncia", b =>
                {
                    b.HasOne("Recetas.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DenuncianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.EtiquetaDeReceta", b =>
                {
                    b.HasOne("Recetas.Dominio.Recetas.Etiqueta", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany("Etiquetas")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Foto", b =>
                {
                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany("Fotos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.IngredienteDeReceta", b =>
                {
                    b.HasOne("Recetas.Dominio.Recetas.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recetas.Dominio.Recetas.Receta", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("Recetas.Dominio.Usuarios.SolicitudDeContrasena", b =>
                {
                    b.HasOne("Recetas.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Recetas.Dominio.Recetas.Receta", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Fotos");

                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
